backend:
  name: git-gateway
  branch: master
  commit_messages:
    create: 'Create {{collection}} “{{slug}}”'
    update: 'Update {{collection}} “{{slug}}”'
    delete: 'Delete {{collection}} “{{slug}}”'
    uploadMedia: '[skip ci] Upload “{{path}}”'
    deleteMedia: '[skip ci] Delete “{{path}}”'

media_folder: static/img
public_folder: /img

collections:
  - name: 'pages'
    label: 'Pages'
    files:
      - file: 'content/pages/about.yml'
        label: 'About'
        name: 'about'
        fields:
          - {
              label: 'Template Key',
              name: 'templateKey',
              widget: 'hidden',
              default: 'about-page',
            }
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'Body', name: 'body', widget: 'markdown' }

      - file: 'content/pages/prices.yml'
        label: 'Prices'
        name: 'prices'
        fields:
          - {
              label: 'Template Key',
              name: 'templateKey',
              widget: 'hidden',
              default: 'prices-page',
            }
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'Body', name: 'body', widget: 'markdown' }

  - name: 'cakes'
    label: 'Cakes'
    folder: 'content/cakes'
    create: true
    fields:
      - {
          label: 'Template Key',
          name: 'templateKey',
          widget: 'hidden',
          default: 'cake-page',
        }
      - { label: 'URL', name: 'slug', widget: 'string' }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Featured Image', name: 'featuredimage', widget: image }
      - { label: 'Description', name: 'desc', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
      - { label: 'Price', name: 'price', widget: 'number' }
      - label: Images
        name: images
        widget: list
        field: { label: Image, name: image, widget: image }

  - name: 'testimonials'
    label: 'Testimonials'
    folder: 'content/testimonials'
    create: true
    fields:
      - {
          label: 'Template Key',
          name: 'templateKey',
          widget: 'hidden',
          default: 'testimonial',
        }
      - { label: 'Name', name: 'name', widget: 'string' }
      - { label: 'Quote', name: 'quote', widget: 'string' }
