- name: 'Cakes'
  link: '/cakes'
- name: 'Instagram'
  link: '/instagram'
- name: 'About'
  link: '/about'
- name: 'Services'
  link: '/services'
- name: 'Gallery'
  link: '/gallery'
- name: 'Testimonials'
  link: '/testimonials'
